"""Reclamation Algorithm page (生息演算) → `__gui_reclamation` task."""

from __future__ import annotations

import tomllib

from PySide6.QtWidgets import (
    QGridLayout,
    QLabel,
    QPlainTextEdit,
    QVBoxLayout,
    QWidget,
)

from .. import maa
from ..runner import TaskRunner
from ..state import AppState
from ..widgets import (
    RunBar,
    bool_field,
    combo_field,
    FieldRow,
    spin_field,
    text_field,
)

TASK_FILE = maa.GUI_PREFIX + "reclamation"

THEMES = ["Tales", "Fire", "Ash"]


class ReclamationPage(QWidget):
    def __init__(self, runner: TaskRunner, state: AppState, parent=None):
        super().__init__(parent)
        self.runner = runner
        self.state = state

        outer = QVBoxLayout(self)
        outer.setContentsMargins(16, 16, 16, 16)
        outer.setSpacing(12)

        title = QLabel("Reclamation Algorithm — 生息演算")
        title.setStyleSheet("font-size: 17px; font-weight: 700;")
        outer.addWidget(title)

        grid = QGridLayout()
        grid.setHorizontalSpacing(18)
        grid.setVerticalSpacing(10)

        self.theme = combo_field(THEMES, editable=True)
        grid.addWidget(FieldRow("Theme", self.theme), 0, 0)

        self.tool_to_craft = text_field("", "e.g. " + "\u6eb6\u5242" + " (Solvent)")
        grid.addWidget(FieldRow("Tool to craft", self.tool_to_craft), 0, 1)

        self.increment_mode = combo_field(["0 — auto-build from scratch", "1 — build only what's missing"])
        grid.addWidget(FieldRow("Increment mode", self.increment_mode), 0, 2)

        self.max_craft = spin_field(0, 0, 99, suffix=" (0 = unlimited)")
        grid.addWidget(FieldRow("Max craft count", self.max_craft), 0, 3)

        self.custom_craft = bool_field()
        grid.addWidget(FieldRow("Enable custom craft list", self.custom_craft), 1, 0)

        self.custom_craft_text = QPlainTextEdit()
        self.custom_craft_text.setFixedHeight(90)
        self.custom_craft_text.setPlaceholderText(
            "TOML array of tables, e.g.\n[{ name = \"\u6eb6\u5242\", num = 2, type = \"Craft\" }]"
        )
        grid.addWidget(FieldRow("Custom craft list", self.custom_craft_text), 1, 1, 1, 3)

        outer.addLayout(grid)

        self.bar = RunBar()
        self.bar.save_requested.connect(self.save)
        self.bar.run_requested.connect(self.save_and_run)
        self.bar.stop_btn.clicked.connect(self.runner.stop)
        outer.addWidget(self.bar)
        outer.addStretch(1)

        self.runner.running_changed.connect(self.bar.set_running)
        self._load()

    # -- form <-> params ------------------------------------------------------

    def to_task_params(self) -> dict:
        params: dict = {}
        theme = self.theme.currentText().strip()
        if theme:
            params["theme"] = theme
        tool = self.tool_to_craft.text().strip()
        if tool:
            params["tool_to_craft"] = tool
        params["increment_mode"] = self.increment_mode.currentIndex()
        if self.max_craft.value():
            params["max_craft_count"] = self.max_craft.value()
        params["enable_custom_craft"] = self.custom_craft.isChecked()
        text = self.custom_craft_text.toPlainText().strip()
        if text:
            try:
                params["custom_craft"] = tomllib.loads("x = " + text)["x"]
            except (tomllib.TOMLDecodeError, KeyError):
                pass  # leave it out; maa-cli will report the error at runtime
        return params

    def _load(self):
        try:
            data = maa.read_task(TASK_FILE)
            if not data.strip():
                return
            parsed = tomllib.loads(data)
            p = (parsed.get("tasks") or [{}])[0].get("params", {})
        except Exception:
            return
        if not p:
            return
        if "theme" in p:
            self.theme.setCurrentText(str(p["theme"]))
        self.tool_to_craft.setText(str(p.get("tool_to_craft", "")))
        if "increment_mode" in p:
            idx = int(p["increment_mode"])
            if 0 <= idx < self.increment_mode.count():
                self.increment_mode.setCurrentIndex(idx)
        self.max_craft.setValue(int(p.get("max_craft_count", 0)))
        self.custom_craft.setChecked(bool(p.get("enable_custom_craft", False)))
        cc = p.get("custom_craft")
        if isinstance(cc, list):
            self.custom_craft_text.setPlainText("\n".join(str(x) for x in cc))

    # -- actions ---------------------------------------------------------------

    def save(self) -> bool:
        maa.write_task(TASK_FILE, maa.task_file_text(
            [("ReclamationAlgorithm", "ReclamationAlgorithm", self.to_task_params())],
            header="# Generated by MaaGui — Reclamation Algorithm"))
        return True

    def save_and_run(self):
        if self.runner.running:
            return
        self.save()
        self.runner.start(TASK_FILE, self.state.profile)
