"""Toolbox tab — the WPF ToolboxView recognitions plus fork utilities.

Sub-tabs mirror the WPF toolbox: Recruitment recognition, OperBox
recognition, Depot recognition (each drives the matching maa-cli task and
shows the results), plus Task Files and Logs from the fork's maagui base.
"""

from __future__ import annotations

import json
import time

from PySide6.QtCore import QSettings
from PySide6.QtGui import QColor, QGuiApplication
from PySide6.QtWidgets import (
    QCheckBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QMessageBox,
    QPushButton,
    QTabWidget,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)
from maagui import maa, prts
from maagui.pages.logs import LogsPage
from maagui.pages.taskfiles import TaskFilesPage
from maagui.runner import TaskRunner

from . import theme
from .wpfwidgets import SubTabRow

RARITY_COLORS = ["#c0c0c0", "#c0c0c0", "#dbd856", "#c27cd6", "#e69742", "#ff4800"]


def _display_name(cn_name: str, cn2en: dict) -> str:
    en = cn2en.get(cn_name, "")
    return f"{cn_name} ({en})" if en and en != cn_name else cn_name


class RecognitionView(QWidget):
    """Common shell for a recognition sub-tab: options row + Start + output."""

    TASK_FILE = ""
    START_LABEL = "Start recognition"

    def __init__(self, runner: TaskRunner, settings: QSettings, state, parent=None):
        super().__init__(parent)
        self.runner = runner
        self.settings = settings
        self.state = state
        self.setObjectName("pageRoot")

        self.lay = QVBoxLayout(self)
        self.lay.setContentsMargins(0, 0, 0, 0)
        self.lay.setSpacing(10)

        opts = QHBoxLayout()
        self._build_options(opts)
        opts.addStretch(1)
        self.start_btn = QPushButton(self.START_LABEL)
        self.start_btn.setObjectName("toolboxStart")
        self.start_btn.clicked.connect(self.start)
        opts.addWidget(self.start_btn)
        self.lay.addLayout(opts)

        self._build_body()

        self.runner.running_changed.connect(self._on_running_changed)

    # subclasses override these ------------------------------------------------
    def _build_options(self, layout):
        pass

    def _build_body(self):
        self.output = QTextEdit()
        self.output.setReadOnly(True)
        self.output.setPlaceholderText("Recognition results appear here…")
        self.lay.addWidget(self.output, 1)

    # helpers -----------------------------------------------------------------
    def busy_check(self) -> bool:
        if self.runner.running:
            QMessageBox.information(self, "Busy", "A task is already running.")
            return True
        return False

    def _run_task(self, name: str, task_type: str, params: dict):
        maa.write_task(name, maa.task_file_text(
            [(task_type, task_type, params)],
            header=f"# Generated by MaaGui3 — {task_type}"))
        self.runner.start(name, self.state.profile)

    def _on_running_changed(self, running: bool):
        self.start_btn.setEnabled(not running)


class RecruitRecognition(RecognitionView):
    """Recruitment recognition — run Recruit with an empty confirm list so
    MAA only analyses the slots and reports the tags."""

    TASK_FILE = maa.GUI_PREFIX + "toolbox_recruit"
    START_LABEL = "Start to recognize"

    def _build_options(self, layout):
        self.auto_time = QCheckBox("Auto set 9:00 operation time")
        self.auto_time.setChecked(self.settings.value("toolbox/recruit_auto_time", True, bool))
        self.auto_time.toggled.connect(
            lambda on: self.settings.setValue("toolbox/recruit_auto_time", on))
        layout.addWidget(self.auto_time)
        hint = QLabel("Runs recruitment analysis without confirming any slot.")
        hint.setStyleSheet(f"color: {theme.TEXT_DIM};")
        layout.addWidget(hint)

    def _build_body(self):
        super()._build_body()
        self.runner.log_line.connect(self._on_log_line)
        self.runner.finished.connect(self._on_finished)

    def start(self):
        if self.busy_check():
            return
        self.output.clear()
        params: dict = {"select": [3, 4, 5, 6], "confirm": [], "refresh": False}
        if self.auto_time.isChecked():
            params["set_time"] = True
            params["recruitment_time"] = "9:00"
        self._run_task(self.TASK_FILE, "Recruit", params)

    def _on_log_line(self, line: str):
        if self.runner.running and self.runner.task_name == self.TASK_FILE:
            self.output.append(line)

    def _on_finished(self, code: int, summary: str):
        if self.runner.task_name == self.TASK_FILE:
            self.output.append(summary)


class OperBoxRecognition(RecognitionView):
    """OperBox recognition — owned / not-owned tables like the WPF toolbox."""

    TASK_FILE = maa.GUI_PREFIX + "toolbox_operbox"
    START_LABEL = "Start to identify"

    def _build_options(self, layout):
        self.last_sync = QLabel(f"Last sync time: "
                                f"{self.settings.value('toolbox/operbox_sync', '—')}")
        self.last_sync.setStyleSheet(f"color: {theme.TEXT_DIM};")
        layout.addWidget(self.last_sync)
        export = QPushButton("Export")
        export.setToolTip("Copy the roster JSON to the clipboard")
        export.clicked.connect(self._export)
        layout.addWidget(export)

    def _build_body(self):
        self.tables = QTabWidget()
        self.have_table = self._make_table(["Name", "Rarity", "Level", "Potential"])
        self.not_have_table = self._make_table(["Name", "Rarity"])
        self.tables.addTab(self.have_table, "Owned")
        self.tables.addTab(self.not_have_table, "Not owned")
        self.lay.addWidget(self.tables, 1)
        self.runner.finished.connect(self._on_finished)

    @staticmethod
    def _make_table(headers: list[str]) -> QTableWidget:
        t = QTableWidget(0, len(headers))
        t.setHorizontalHeaderLabels(headers)
        t.verticalHeader().setVisible(False)
        t.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        t.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        header = t.horizontalHeader()
        for i in range(len(headers) - 1):
            header.setSectionResizeMode(i, QHeaderView.ResizeMode.ResizeToContents)
        header.setSectionResizeMode(len(headers) - 1, QHeaderView.ResizeMode.Stretch)
        return t

    def start(self):
        if self.busy_check():
            return
        self._run_task(self.TASK_FILE, "OperBox", {})

    def _fill(self, table: QTableWidget, rows: list[tuple[str, int, str, str]], rarity_col: int):
        table.setRowCount(0)
        for name, rarity, *rest in rows:
            row = table.rowCount()
            table.insertRow(row)
            table.setItem(row, 0, QTableWidgetItem(name))
            ritem = QTableWidgetItem("★" * max(1, min(rarity, 6)))
            ritem.setForeground(QColor(RARITY_COLORS[min(rarity, len(RARITY_COLORS) - 1)]))
            table.setItem(row, rarity_col, ritem)
            for offset, text in enumerate(rest):
                table.setItem(row, rarity_col + 1 + offset, QTableWidgetItem(text))

    def _on_finished(self, code: int, summary: str):
        if self.runner.task_name != self.TASK_FILE:
            return
        msg = maa.latest_operbox_message()
        if msg is None:
            QMessageBox.warning(
                self, "OperBox recognition",
                f"{summary}\n\nCould not read the roster from MaaCore's log — "
                "was the game on the home screen?")
            return
        details = msg.get("details") or {}
        own = [o for o in (details.get("own_opers") or []) if (o or {}).get("name")]
        all_ops = [o for o in (details.get("all_opers") or []) if (o or {}).get("name")]
        cn2en, en2cn = prts.load_oper_names()

        def to_cn(n: str) -> str:
            return prts._to_cn(n, cn2en, en2cn)

        own_cns = {to_cn(o["name"]) for o in own}
        self._fill(
            self.have_table,
            [(_display_name(to_cn(o["name"]), cn2en),
              int(o.get("rarity", int(o.get("elite", 0)) + 1)),
              str(o.get("level", "")), str(o.get("potential", "")))
             for o in sorted(own, key=lambda x: -int(x.get("rarity", int(x.get("elite", 0)) + 1)))],
            rarity_col=1)
        self._fill(
            self.not_have_table,
            [(_display_name(to_cn(o["name"]), cn2en),
              int(o.get("rarity", int(o.get("elite", 0)) + 1)))
             for o in sorted(all_ops, key=lambda x: -int(x.get("rarity", int(x.get("elite", 0)) + 1)))
             if to_cn(o["name"]) not in own_cns],
            rarity_col=1)

        stamp = time.strftime("%Y-%m-%d %H:%M")
        self.last_sync.setText(f"Last sync time: {stamp}")
        self.settings.setValue("toolbox/operbox_sync", stamp)

    def _export(self):
        msg = maa.latest_operbox_message()
        if msg:
            QGuiApplication.clipboard().setText(
                json.dumps(msg.get("details", {}), ensure_ascii=False))


class DepotRecognition(RecognitionView):
    """Depot recognition — inventory scan; results stream into the output."""

    TASK_FILE = maa.GUI_PREFIX + "toolbox_depot"
    START_LABEL = "Start to identify"

    def _build_options(self, layout):
        self.last_sync = QLabel(f"Last sync time: "
                                f"{self.settings.value('toolbox/depot_sync', '—')}")
        self.last_sync.setStyleSheet(f"color: {theme.TEXT_DIM};")
        layout.addWidget(self.last_sync)

    def _build_body(self):
        super()._build_body()
        self.runner.log_line.connect(self._on_log_line)
        self.runner.finished.connect(self._on_finished)

    def start(self):
        if self.busy_check():
            return
        self.output.clear()
        self._run_task(self.TASK_FILE, "Depot", {})

    def _on_log_line(self, line: str):
        if self.runner.running and self.runner.task_name == self.TASK_FILE:
            self.output.append(line)

    def _on_finished(self, code: int, summary: str):
        if self.runner.task_name == self.TASK_FILE:
            self.output.append(summary)
            self.settings.setValue("toolbox/depot_sync", time.strftime("%Y-%m-%d %H:%M"))
            self.last_sync.setText(f"Last sync time: "
                                   f"{self.settings.value('toolbox/depot_sync', '—')}")


class ToolboxPage(QWidget):
    def __init__(self, runner: TaskRunner, settings: QSettings, state, parent=None):
        super().__init__(parent)
        self.runner = runner
        self.settings = settings
        self.state = state

        outer = QVBoxLayout(self)
        outer.setContentsMargins(16, 12, 16, 12)
        outer.setSpacing(10)

        self.tabs = SubTabRow([
            "Recruitment recognition", "OperBox recognition", "Depot recognition",
            "Task Files", "Logs",
        ])
        outer.addWidget(self.tabs)

        self.recruit_view = RecruitRecognition(runner, settings, state)
        self.operbox_view = OperBoxRecognition(runner, settings, state)
        self.depot_view = DepotRecognition(runner, settings, state)
        self.taskfiles_view = TaskFilesPage(runner, state)
        self.logs_view = LogsPage(runner)

        self.views = [
            self.recruit_view, self.operbox_view, self.depot_view,
            self.taskfiles_view, self.logs_view,
        ]
        for v in self.views:
            outer.addWidget(v, 1)
        self.tabs.changed.connect(self._on_tab)
        self._on_tab(0)

    def _on_tab(self, index: int):
        for i, v in enumerate(self.views):
            v.setVisible(i == index)

    def shutdown(self):
        self.logs_view.shutdown()
