"""maa-cli integration layer: paths, versions, profile/task CRUD, device checks.

Everything the GUI knows about maa-cli lives here, so the pages stay thin.
Profile files are user-authored TOML that may contain comments — when the GUI
edits a profile it updates scalar `key = value` lines *in place* (preserving
comments and unknown fields), and only appends keys that don't exist yet.
Task files, on the other hand, are fully generated by the GUI (names prefixed
``__gui_``) and serialized with the small TOML writer at the bottom of this
module (``tomli_w`` is not guaranteed to be installed).
"""

from __future__ import annotations

import os
import json
import re
import shutil
import subprocess
import tomllib
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths / versions
# ---------------------------------------------------------------------------

_CONFIG_DIR = Path(os.environ.get("MAA_CONFIG_DIR", Path.home() / ".config" / "maa"))


def maa_binary() -> str | None:
    return shutil.which("maa")


def _dir(kind: str) -> Path:
    """Resolve a maa-cli directory (`maa dir <kind>`), falling back to defaults."""
    bin_ = maa_binary()
    if bin_:
        try:
            out = subprocess.run(
                [bin_, "dir", kind], capture_output=True, text=True, timeout=10
            )
            if out.returncode == 0:
                return Path(out.stdout.strip())
        except (OSError, subprocess.TimeoutExpired):
            pass
    if kind == "config":
        return _CONFIG_DIR
    if kind == "log":
        return Path.home() / ".local" / "state" / "maa" / "debug"
    return Path.home() / ".cache" / "maa"


def config_dir() -> Path:
    return _dir("config")


def dir_data() -> Path:
    return _dir("data")


def profiles_dir() -> Path:
    return config_dir() / "profiles"


def tasks_dir() -> Path:
    return config_dir() / "tasks"


def log_dir() -> Path:
    return _dir("log")


def versions() -> tuple[str, str]:
    """Return (maa-cli version, MaaCore version), or ("", "") if unavailable."""
    bin_ = maa_binary()
    if not bin_:
        return ("", "")
    try:
        out = subprocess.run([bin_, "version"], capture_output=True, text=True, timeout=15)
        if out.returncode != 0:
            return ("", "")
        cli = core = ""
        for line in out.stdout.splitlines():
            if line.startswith("maa-cli"):
                cli = line.split()[-1]
            elif line.startswith("MaaCore"):
                core = line.split()[-1]
        return (cli, core)
    except (OSError, subprocess.TimeoutExpired):
        return ("", "")


# ---------------------------------------------------------------------------
# Profiles
# ---------------------------------------------------------------------------

#: (section, key) pairs the GUI can edit. Values are all scalars, so the
#: in-place line rewriting in :func:`set_profile_fields` stays simple.
PROFILE_FIELDS: dict[str, list[str]] = {
    "connection": ["preset", "adb_path", "address", "config", "window_name", "focus_for_keys"],
    "resource": ["global_resource", "platform_diff_resource", "user_resource"],
    "static_options": ["cpu_ocr", "gpu_ocr"],
    "instance_options": [
        "touch_mode",
        "deployment_with_pause",
        "adb_lite_enabled",
        "kill_adb_on_exit",
    ],
}


def list_profiles() -> list[str]:
    d = profiles_dir()
    if not d.is_dir():
        return []
    return sorted(p.stem for p in d.iterdir() if p.suffix in (".toml", ".json", ".yaml", ".yml"))


def ensure_default_profile() -> str:
    """Create a ``default`` profile on first run so the GUI never starts with
    an empty profile list. Returns the name of the profile to select."""
    if not list_profiles():
        write_profile("default", {"connection": {"preset": "", "window_name": "Arknights"}})
        return "default"
    return ""


def read_profile(name: str) -> dict:
    path = profiles_dir() / f"{name}.toml"
    if not path.is_file():
        # try other formats
        for ext in (".json", ".yaml", ".yml"):
            p = profiles_dir() / f"{name}{ext}"
            if p.is_file():
                path = p
                break
    if not path.is_file():
        return {}
    with open(path, "rb") as f:
        try:
            return tomllib.load(f)
        except tomllib.TOMLDecodeError:
            return {}


def _profile_path(name: str) -> Path:
    return profiles_dir() / f"{name}.toml"


def _fmt_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{value}"'


_SCALAR_RE = re.compile(r'^(\s*[A-Za-z_][A-Za-z0-9_]*\s*=\s*)(.+?)(\s*(?:#.*)?)$')


def set_profile_fields(name: str, values: dict[str, str | int | float | bool]) -> None:
    """Update scalar fields of a profile in place, preserving comments.

    ``values`` uses ``"section.key"`` as keys. Empty/None values remove the
    line (so an empty address falls back to maa-cli auto-detection); missing
    keys are appended to the end of their section.
    """
    profiles_dir().mkdir(parents=True, exist_ok=True)
    path = _profile_path(name)
    text = path.read_text() if path.is_file() else ""

    # map section -> {key: line_index}
    section_lines: dict[str, list[int]] = {}
    current: str | None = None
    lines = text.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"^\s*\[([^\]]+)\]\s*$", line)
        if m:
            current = m.group(1).strip()
            section_lines.setdefault(current, []).append(i)
            continue
        if current and line.strip() and not line.strip().startswith("#"):
            section_lines.setdefault(current, []).append(i)

    for key, value in values.items():
        section, _, field = key.partition(".")
        replaced = False
        for i in section_lines.get(section, []):
            line = lines[i]
            m = re.match(rf"^\s*({re.escape(field)}\s*=\s*)(.+?)(\s*(?:#.*)?)$", line)
            if m and not line.lstrip().startswith("["):
                if value is None or value == "":
                    lines[i] = ""  # remove the line
                else:
                    lines[i] = f"{m.group(1)}{_fmt_scalar(value)}{m.group(3)}"
                replaced = True
                break
        if replaced or value is None or value == "":
            continue
        # key not present: insert right after the section header
        if section in section_lines and section_lines[section]:
            anchor = section_lines[section][0]
        else:
            # new section: append at end of file
            if lines and lines[-1].strip():
                lines.append("")
            lines.append(f"[{section}]")
            anchor = len(lines) - 1
            section_lines[section] = [anchor]
        lines.insert(anchor + 1, f"{field} = {_fmt_scalar(value)}")
        section_lines[section] = [i + 1 if i > anchor else i for i in section_lines[section]]

    # drop blank lines that were emptied out
    out = [ln for ln in lines if ln != "" or False]
    out = []
    blank = False
    for ln in lines:
        if ln.strip() == "":
            if blank:
                continue
            blank = True
        else:
            blank = False
        out.append(ln)
    path.write_text("\n".join(out).rstrip() + "\n")


def write_profile(name: str, data: dict) -> None:
    """Full overwrite (used by 'duplicate profile')."""
    profiles_dir().mkdir(parents=True, exist_ok=True)
    (_profile_path(name)).write_text(_dumps(data) + "\n")


def delete_profile(name: str) -> None:
    path = _profile_path(name)
    if path.is_file():
        path.unlink()


def duplicate_profile(src: str, dst: str) -> None:
    profiles_dir().mkdir(parents=True, exist_ok=True)
    src_path = _profile_path(src)
    dst_path = _profile_path(dst)
    if src_path.is_file():
        dst_path.write_text(src_path.read_text())


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------

GUI_PREFIX = "__gui_"

TASK_TYPES = [
    "StartUp", "CloseDown", "Fight", "Recruit", "Infrast", "Mall", "Award",
    "Roguelike", "Copilot", "SSSCopilot", "Depot", "OperBox",
    "ReclamationAlgorithm", "Custom",
]

#: (type, human label) used in the task-file editor.
TASK_TYPE_LABELS = {
    "StartUp": "StartUp — launch the game client",
    "CloseDown": "CloseDown — close the game client",
    "Fight": "Fight — auto-farm a stage",
    "Recruit": "Recruit — auto-recruitment",
    "Infrast": "Infrast — base shift / facilities",
    "Mall": "Mall — credit shop shopping",
    "Award": "Award — claim daily/weekly awards",
    "Roguelike": "Roguelike — Integrated Strategies farming",
    "Copilot": "Copilot — run a copilot JSON",
    "SSSCopilot": "SSSCopilot — Stationary Security Service copilot",
    "Depot": "Depot — depot item recognition",
    "OperBox": "OperBox — operator box recognition",
    "ReclamationAlgorithm": "ReclamationAlgorithm — Reclamation Algorithm farming",
    "Custom": "Custom — custom task with MaaCore interface",
}


def list_tasks() -> list[str]:
    d = tasks_dir()
    if not d.is_dir():
        return []
    names = sorted(p.stem for p in d.iterdir() if p.suffix in (".toml", ".json", ".yaml", ".yml"))
    return names


def read_task(name: str) -> str:
    d = tasks_dir()
    for ext in (".toml", ".json", ".yaml", ".yml"):
        p = d / f"{name}{ext}"
        if p.is_file():
            return p.read_text()
    return ""


def write_task(name: str, text: str) -> None:
    tasks_dir().mkdir(parents=True, exist_ok=True)
    (tasks_dir() / f"{name}.toml").write_text(text)


def delete_task(name: str) -> None:
    for ext in (".toml", ".json", ".yaml", ".yml"):
        p = tasks_dir() / f"{name}{ext}"
        if p.is_file():
            p.unlink()


def task_path(name: str) -> Path:
    return tasks_dir() / f"{name}.toml"


# ---------------------------------------------------------------------------
# Task file generation
# ---------------------------------------------------------------------------

def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        # escape backslash, quote, control chars
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{_toml_key(k)} = {_toml_value(x)}" for k, x in v.items()) + " }"
    return str(v)


def _toml_key(k: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_-]+", k):
        return k
    return _toml_value(k)


def task_file_text(subtasks: list[tuple[str, str, dict]], header: str = "") -> str:
    """Serialize subtasks [(name, type, params)] into a maa-cli task file."""
    parts = []
    if header:
        parts.append(header.rstrip())
    for i, (name, ttype, params) in enumerate(subtasks):
        if parts and parts[-1].strip():
            parts.append("")
        parts.append("[[tasks]]")
        if name:
            parts.append(f"name = {_toml_value(name)}")
        parts.append(f"type = {_toml_value(ttype)}")
        if params:
            parts.append("")
            parts.append("[tasks.params]")
            for k, v in params.items():
                if v is None or v == "":
                    continue  # skip empty params (empty arrays are kept —
                    # MaaCore requires e.g. Recruit's select/confirm arrays)
                parts.append(f"{_toml_key(k)} = {_toml_value(v)}")
    return "\n".join(parts).rstrip() + "\n"


def _dumps(data: dict) -> str:
    """Small TOML writer for flat config files (profiles)."""
    out = []
    for section, fields in data.items():
        out.append(f"[{section}]")
        for k, v in fields.items():
            if v is None or v == "":
                continue
            out.append(f"{k} = {_toml_value(v)}")
        out.append("")
    return "\n".join(out).rstrip()


# ---------------------------------------------------------------------------
# Device / environment checks
# ---------------------------------------------------------------------------

def check_device(
    preset: str = "", address: str = "", adb_path: str = "", window_name: str = ""
) -> tuple[bool, str]:
    """Check whether the device is reachable. Returns (ok, detail)."""
    try:
        if preset.lower() == "window":
            name = window_name or "Arknights"
            try:
                r = subprocess.run(
                    ["xdotool", "search", "--name", name],
                    capture_output=True, text=True, timeout=10,
                )
            except FileNotFoundError:
                return False, "xdotool not found (install xdotool)"
            wins = [ln for ln in r.stdout.splitlines() if ln.strip()]
            if not wins:
                return False, f'no X11 window titled "{name}"'
            return True, f'window "{name}" found ({(len(wins))} match(es))'
        if preset.lower() == "waydroid":
            r = subprocess.run(
                ["waydroid", "status"], capture_output=True, text=True, timeout=10
            )
            if r.returncode == 0:
                for line in r.stdout.splitlines():
                    if "Session:" in line and "RUNNING" in line.upper():
                        return True, "Waydroid session running"
                return False, r.stdout.strip() or "Waydroid session not running"
            return False, (r.stderr or r.stdout).strip() or "waydroid status failed"

        adb = adb_path or shutil.which("adb") or "adb"
        r = subprocess.run(
            [adb, "devices"], capture_output=True, text=True, timeout=10
        )
        if r.returncode != 0:
            return False, (r.stderr or r.stdout).strip() or "adb not found"
        lines = [ln for ln in r.stdout.splitlines()[1:] if ln.strip()]
        if not lines:
            return False, "no adb devices"
        target = address or "emulator-5554"
        for ln in lines:
            dev, _, state = ln.partition("\t")
            if dev == target:
                return state.strip() == "device", f"{dev} [{state.strip()}]"
        return True, f"{len(lines)} device(s), {target} not listed"
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, str(e)


def run_sync(args: list[str], timeout: int = 120) -> subprocess.CompletedProcess:
    """Run a maa-cli subcommand synchronously (used for quick actions)."""
    return subprocess.run(
        [maa_binary()] + args, capture_output=True, text=True, timeout=timeout
    )


_OPERBOX_RE = re.compile(r'SubTaskExtraInfo (\{.*\})')
_OPERBOX_TASKCHAIN_RE = re.compile(r'"taskchain"\s*:\s*"OperBox"')


def latest_operbox_message() -> dict | None:
    """Parse the newest OperBox callback JSON from MaaCore's asst.log.

    MaaCore logs the full `SubTaskExtraInfo` message (including the operator
    roster) as one compact JSON line — far more reliable than scraping the
    pretty-printed stream from maa-cli's logger.
    """
    path = log_dir() / "asst.log"
    if not path.is_file():
        return None
    try:
        size = path.stat().st_size
        with open(path, "rb") as f:
            f.seek(max(0, size - 6 * 1024 * 1024))  # tail ~6 MB
            tail = f.read().decode("utf-8", errors="replace")
    except OSError:
        return None
    for line in reversed(tail.splitlines()):
        if not _OPERBOX_TASKCHAIN_RE.search(line):
            continue
        m = _OPERBOX_RE.search(line)
        if not m:
            continue
        try:
            msg = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        if msg.get("taskchain") == "OperBox":
            return msg
    return None


def open_in_file_manager(path: Path) -> None:
    subprocess.Popen(["xdg-open", str(path)])


def ensure_dirs() -> None:
    profiles_dir().mkdir(parents=True, exist_ok=True)
    tasks_dir().mkdir(parents=True, exist_ok=True)


if __name__ == "__main__":
    # tiny self-test
    ensure_dirs()
    print("maa binary:", maa_binary())
    print("config dir:", config_dir())
    print("profiles:", list_profiles())
    print("tasks:", list_tasks())
    print("versions:", versions())
